default exec64
menu title U-Boot Menu (Milk-V Mars)
prompt 1
timeout 20

label exec64
    menu label Exec64 RTOS (Final Stability Fix)
    linux /Exec64
    fdtdir /dtbs
    append console=ttyS0,115200 earlycon
	
